var searchModuleIndex = [
"nix",
];

var searchIndex = [
"new_aliases",
"Aliases",
"add",
"has",
"get",
"del",
"read",
"write",
"hostname",
"dir_db",
"dir_cfg",
"processes",
"get_linux_listening_tcp",
"get_linux_listening_udp",
"User",
"username_current",
"username_by_uid",
"uid_by_username",
"user_by_name",
"user_by_uid",
"is_root",
"is_user",
"user_has_home",
"user_in_group",
"user_dir_config",
"user_dir_bin",
"users",
];

var searchModuleData = [
["","nix.html"],
];

var searchData = [
["nix","new_aliases returns the aliases struct populated with users and the provided pat","nix.html#new_aliases","fn "],
["nix","","nix.html#Aliases","type "],
["nix","add adds an alias <from> to be forwarded to <to>","nix.html#Aliases.add","fn (Aliases)"],
["nix","has returns true/false after checking the databsae for the alias","nix.html#Aliases.has","fn (Aliases)"],
["nix","get returns the receipient for alias","nix.html#Aliases.get","fn (Aliases)"],
["nix","del with remove the alias from the database","nix.html#Aliases.del","fn (Aliases)"],
["nix","read reads the aliases file in to memory","nix.html#Aliases.read","fn (Aliases)"],
["nix","write writes the aliases from memory to file","nix.html#Aliases.write","fn (Aliases)"],
["nix","","nix.html#hostname","fn "],
["nix","dir_db returns the path to the applications database folder","nix.html#dir_db","fn "],
["nix","dir_cfg returns the path to the applications configuration folder","nix.html#dir_cfg","fn "],
["nix","processes(): Aggregates TCP and UDP listeners, then iterates to replace \"inode=","nix.html#processes","fn "],
["nix","get_linux_listening_tcp() Parsing of /proc/net/tcp. Skips header, filters by sta","nix.html#get_linux_listening_tcp","fn "],
["nix","get_linux_listening_udp(): Parsing of /proc/net/udp. Skips header, filters by st","nix.html#get_linux_listening_udp","fn "],
["nix","","nix.html#User","struct "],
["nix","","nix.html#username_current","fn "],
["nix","username_by_uid gets the users username from uid","nix.html#username_by_uid","fn "],
["nix","uid_by_username gets the username from uid","nix.html#uid_by_username","fn "],
["nix","by_name gets the users /etc/passwd data by username","nix.html#user_by_name","fn "],
["nix","by_uid gets the users /etc/passwd data by user id","nix.html#user_by_uid","fn "],
["nix","is_root return true if current user is efectively root","nix.html#is_root","fn "],
["nix","","nix.html#is_user","fn "],
["nix","user_has_home checks if the username has a home directory according to /etc/pass","nix.html#user_has_home","fn "],
["nix","user_in_group checks if the user has given group privliages","nix.html#user_in_group","fn "],
["nix","","nix.html#user_dir_config","fn "],
["nix","","nix.html#user_dir_bin","fn "],
["nix","users returns users. all data passwd and group","nix.html#users","fn "],
];

