var searchModuleIndex = [
"README",
"gittool",
"highlighter",
"markdown",
"nix",
"upgrade",
];

var searchIndex = [
"context_help",
"context_git",
"context_v",
"GitInfo",
"fields",
"commit",
"Config",
"fields",
"get_info",
"git_version",
"bump_version",
"check_state",
"SyntaxDef",
"PatternItem",
"Manager",
"highlight_html",
"new_manager",
"to_html",
"ParentType",
"HtmlTransformer",
"DefaultHtmlTransformer",
"transform_attribute",
"transform_content",
"config_set",
"AttrTransformerFn",
"AttrTransformer",
"transform_attribute",
"transform_content",
"config_set",
"ContentTransformerFn",
"transform_attribute",
"transform_content",
"config_set",
"HtmlRenderer",
"to_html_experimental",
"MD_BLOCKTYPE",
"MD_TEXTTYPE",
"MD_SPANTYPE",
"MD_ALIGN",
"C.MD_PARSER",
"C.MD_ATTRIBUTE",
"C.MD_BLOCK_UL_DETAIL",
"C.MD_BLOCK_OL_DETAIL",
"C.MD_BLOCK_LI_DETAIL",
"C.MD_BLOCK_H_DETAIL",
"C.MD_BLOCK_CODE_DETAIL",
"C.MD_BLOCK_TD_DETAIL",
"C.MD_SPAN_A_DETAIL",
"C.MD_SPAN_IMG_DETAIL",
"C.MD_SPAN_WIKILINK_DETAIL",
"new",
"PlaintextRenderer",
"str",
"to_plain",
"Renderer",
"render",
"new_aliases",
"Aliases",
"add",
"has",
"get",
"del",
"read",
"write",
"is_email_address",
"hostname",
"distribution",
"uptime",
"dir_db",
"dir_cfg",
"processes",
"get_linux_listening_tcp",
"get_linux_listening_udp",
"User",
"username_current",
"username_by_uid",
"uid_by_username",
"user_by_name",
"user_by_uid",
"is_root",
"is_user",
"user_has_home",
"user_in_group",
"user_dir_config",
"user_dir_bin",
"users",
"Manager",
"check",
"from_remote",
"run",
];

var searchModuleData = [
["","index.html"],
["1. A module (gittool) and a command line tool (commit); to git add, git tag, git","gittool.html"],
["A lightweight, native V module to inject (Prism-compatible css) syntax highlight","highlighter.html"],
["Markdown module for V. For now, it uses the [md4c](https://github.com/mity/md4c)","markdown.html"],
["tamer/nix","nix.html"],
["A lightweight V module to automatically rebuild and restart your application whe","upgrade.html"],
];

var searchData = [
["gittool","","gittool.html#context_help","fn "],
["gittool","","gittool.html#context_git","fn "],
["gittool","","gittool.html#context_v","fn "],
["gittool","GitInfo git information","gittool.html#GitInfo","struct "],
["gittool","","gittool.html#GitInfo.fields","fn (GitInfo)"],
["gittool","Attach the logic directly to GitInfo","gittool.html#GitInfo.commit","fn (GitInfo)"],
["gittool","","gittool.html#Config","struct "],
["gittool","","gittool.html#Config.fields","fn (Config)"],
["gittool","","gittool.html#get_info","fn "],
["gittool","","gittool.html#git_version","fn "],
["gittool","","gittool.html#bump_version","fn "],
["gittool","","gittool.html#check_state","fn "],
["highlighter","","highlighter.html#SyntaxDef","struct "],
["highlighter","","highlighter.html#PatternItem","struct "],
["highlighter","","highlighter.html#Manager","struct "],
["highlighter","","highlighter.html#Manager.highlight_html","fn (Manager)"],
["highlighter","","highlighter.html#new_manager","fn "],
["markdown","","markdown.html#to_html","fn "],
["markdown","","markdown.html#ParentType","type "],
["markdown","HtmlTransformer transforms converted HTML elements (limited to attribute and con","markdown.html#HtmlTransformer","interface "],
["markdown","","markdown.html#DefaultHtmlTransformer","struct "],
["markdown","","markdown.html#DefaultHtmlTransformer.transform_attribute","fn (DefaultHtmlTransformer)"],
["markdown","","markdown.html#DefaultHtmlTransformer.transform_content","fn (DefaultHtmlTransformer)"],
["markdown","","markdown.html#DefaultHtmlTransformer.config_set","fn (DefaultHtmlTransformer)"],
["markdown","","markdown.html#AttrTransformerFn","type "],
["markdown","","markdown.html#AttrTransformer","struct "],
["markdown","","markdown.html#AttrTransformer.transform_attribute","fn (AttrTransformer)"],
["markdown","","markdown.html#AttrTransformer.transform_content","fn (AttrTransformer)"],
["markdown","","markdown.html#AttrTransformer.config_set","fn (AttrTransformer)"],
["markdown","","markdown.html#ContentTransformerFn","type "],
["markdown","","markdown.html#ContentTransformerFn.transform_attribute","fn (ContentTransformerFn)"],
["markdown","","markdown.html#ContentTransformerFn.transform_content","fn (ContentTransformerFn)"],
["markdown","","markdown.html#ContentTransformerFn.config_set","fn (ContentTransformerFn)"],
["markdown","","markdown.html#HtmlRenderer","struct "],
["markdown","","markdown.html#to_html_experimental","fn "],
["markdown","","markdown.html#MD_BLOCKTYPE","enum "],
["markdown","","markdown.html#MD_TEXTTYPE","enum "],
["markdown","","markdown.html#MD_SPANTYPE","enum "],
["markdown","","markdown.html#MD_ALIGN","enum "],
["markdown","","markdown.html#C.MD_PARSER","struct "],
["markdown","","markdown.html#C.MD_ATTRIBUTE","struct "],
["markdown","","markdown.html#C.MD_BLOCK_UL_DETAIL","struct "],
["markdown","","markdown.html#C.MD_BLOCK_OL_DETAIL","struct "],
["markdown","","markdown.html#C.MD_BLOCK_LI_DETAIL","struct "],
["markdown","","markdown.html#C.MD_BLOCK_H_DETAIL","struct "],
["markdown","","markdown.html#C.MD_BLOCK_CODE_DETAIL","struct "],
["markdown","","markdown.html#C.MD_BLOCK_TD_DETAIL","struct "],
["markdown","","markdown.html#C.MD_SPAN_A_DETAIL","struct "],
["markdown","","markdown.html#C.MD_SPAN_IMG_DETAIL","struct "],
["markdown","","markdown.html#C.MD_SPAN_WIKILINK_DETAIL","struct "],
["markdown","","markdown.html#new","fn "],
["markdown","","markdown.html#PlaintextRenderer","struct "],
["markdown","","markdown.html#PlaintextRenderer.str","fn (PlaintextRenderer)"],
["markdown","","markdown.html#to_plain","fn "],
["markdown","Renderer represents an entity that accepts incoming data and renders the content","markdown.html#Renderer","interface "],
["markdown","render parses and renders a given markdown string based on the renderer.","markdown.html#render","fn "],
["nix","new_aliases returns the aliases struct populated with users and the provided pat","nix.html#new_aliases","fn "],
["nix","","nix.html#Aliases","type "],
["nix","add adds an alias <from> to be forwarded to <to>","nix.html#Aliases.add","fn (Aliases)"],
["nix","has returns true/false after checking the databsae for the alias","nix.html#Aliases.has","fn (Aliases)"],
["nix","get returns the receipient for alias","nix.html#Aliases.get","fn (Aliases)"],
["nix","del with remove the alias from the database","nix.html#Aliases.del","fn (Aliases)"],
["nix","read reads the aliases file into memory","nix.html#Aliases.read","fn (Aliases)"],
["nix","write writes the aliases from memory to file","nix.html#Aliases.write","fn (Aliases)"],
["nix","","nix.html#is_email_address","fn "],
["nix","","nix.html#hostname","fn "],
["nix","","nix.html#distribution","fn "],
["nix","","nix.html#uptime","fn "],
["nix","dir_db returns the path to the applications database folder","nix.html#dir_db","fn "],
["nix","dir_cfg returns the path to the applications configuration folder","nix.html#dir_cfg","fn "],
["nix","processes(): Aggregates TCP and UDP listeners, then iterates to replace \"inode=","nix.html#processes","fn "],
["nix","get_linux_listening_tcp() Parsing of /proc/net/tcp. Skips header, filters by sta","nix.html#get_linux_listening_tcp","fn "],
["nix","get_linux_listening_udp(): Parsing of /proc/net/udp. Skips header, filters by st","nix.html#get_linux_listening_udp","fn "],
["nix","","nix.html#User","struct "],
["nix","","nix.html#username_current","fn "],
["nix","username_by_uid gets the users username from uid","nix.html#username_by_uid","fn "],
["nix","uid_by_username gets the username from uid","nix.html#uid_by_username","fn "],
["nix","by_name gets the users /etc/passwd data by username","nix.html#user_by_name","fn "],
["nix","by_uid gets the users /etc/passwd data by user id","nix.html#user_by_uid","fn "],
["nix","is_root return true if current user is efectively root","nix.html#is_root","fn "],
["nix","","nix.html#is_user","fn "],
["nix","user_has_home checks if the username has a home directory according to /etc/pass","nix.html#user_has_home","fn "],
["nix","user_in_group checks if the user has given group privliages","nix.html#user_in_group","fn "],
["nix","","nix.html#user_dir_config","fn "],
["nix","","nix.html#user_dir_bin","fn "],
["nix","users returns users. all data passwd and group","nix.html#users","fn "],
["upgrade","","upgrade.html#Manager","struct "],
["upgrade","","upgrade.html#Manager.check","fn (Manager)"],
["upgrade","","upgrade.html#Manager.from_remote","fn (Manager)"],
["upgrade","","upgrade.html#run","fn "],
];

